# Generated by Django 2.1.5 on 2019-02-04 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='ctext',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
